### ISSUE TITLE
Gm messages not sended to discord

### ISSUE THREAD

**Issue by ForesterDev** [fjaros/wowchat#10]
In my guild there are some GM players. And when they type some message, in chat, their message don't show in discord. The problem is that gm messages are sent by SMSG_GM_MESSAGECHAT, not SMSG_MESSAGECHAT. But wowchat doesn't handle this opcode

**Comment by fjaros** [comment]
Latest release zip file now handles this opcode.

**Comment by ForesterDev** [comment]
It works now, thx
