### ISSUE TITLE
missing .jar file

### ISSUE THREAD

**Issue by jchrist188** [fjaros/wowchat#101]
i attempted to set this up on an Ubuntu 20.04 headless server and am unable to get things started due to a missing jar file:

```
root@bear-monitor:~/wowchat-1.3.8/src/main/resources# java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)`

root@bear-monitor:~/wowchat-1.3.8/src/main/resources# java -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback.xml -jar wowchat.jar wowchat.conf
Error: Unable to access jarfile wowchat.jar
root@bear-monitor:~/wowchat-1.3.8/src/main/resources# java -jar wowchat.jar
Error: Unable to access jarfile wowchat.jar
```

not too familiar with using Java so please let me know if implied instructions were not followed

**Comment by fjaros** [comment]
Please follow the "Run" instructions in the README. You can either compile the project yourself or use the premade release binary in [Releases](https://github.com/fjaros/wowchat/releases/tag/v1.3.8).
