### ISSUE TITLE
Warmane: 2FA mandatory

### ISSUE THREAD

**Issue by nerestaren** [fjaros/wowchat#107]
https://forum.warmane.com/showthread.php?t=460199

```
INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.8
INFO  wowchat.WoWChat$ - Connecting to Discord...
INFO  n.d.jda.api.JDA - Login Successful!
INFO  n.d.j.i.r.WebSocketClient - Connected to WebSocket
INFO  n.d.jda.api.JDA - Finished Loading!
INFO  w.r.RealmConnector - Connecting to realm server logon.warmane.com:3724
WARN  i.n.u.i.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: <redacted>
INFO  w.r.RealmPacketHandlerTBC - Connected! Sending account login information...
ERROR w.r.RealmPacketHandlerTBC - Two factor authentication is enabled for this account. Please disable it or use another account.
``` 

I guess this won't be easy to fix. Thank you in advance.

**Comment by fjaros** [comment]
Implemented in https://github.com/fjaros/wowchat/commit/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf .
Wowchat will now ask you to input the security token into the command line window if the server asks for a 2FA check.

**Comment by abdallah-benelmadjat** [comment]
@nerestaren Hey, can you share part of your wowchat.conf that you have (excluding the login info), I am unable to find a way to make this work. I would really appreciate your help.

**Comment by vorghahn** [comment]
> @nerestaren Hey, can you share part of your wowchat.conf that you have (excluding the login info), I am unable to find a way to make this work. I would really appreciate your help.

Did you get it working? I'm also after assistance on this one.

**Comment by nerestaren** [comment]
@abdallah-benelmadjat I do not have anything weird in my wowchat.conf.

@vorghahn what I did was to log in normally with the IP address of the machine that has the bot, entering the code normally and then, since that IP is already recognized by the system, I just started the bot normally.

**Comment by fjaros** [comment]
This is now implemented by the way. If 2FA is needed, the bot will ask you to input the code during login. Just type it into the bot window. If that's not happening, you can redownload the new version from releases.

**Comment by vorghahn** [comment]
@nerestaren 

2FA doesnt seem to be my issue, I just cannot get in on Warmane at all. I'm trying:

# Global WoW Configurations
wow {
  # You MUST keep this as Mac on Warden (anticheat) enabled servers. Windows Warden is not implemented.
  # Only reason to change this is for servers on which Mac login is not working and also which have Warden disabled.
  platform=Mac

  # Whether to treat server's MotD message as a server SYSTEM message.
  enable_server_motd=1

  version=3.3.5
  realmlist=logon.warmane.com
  realm=Icecrown

As Mac i get a wrong server version error. As Windows i get login successful and then booted out in 10secs from Warden but i never see the char log in the game.

Can you message me on discord please? my username is 'vorghahn'

**Comment by nerestaren** [comment]
@vorghahn I have it like that. It should just work. Maybe you misspelled the character's name?

Either log in first so that the server recognizes the IP and doesn't ask it when you use the bot or log with the bot and input the code via the program, as @fjaros says.

**Comment by vorghahn** [comment]
So you're running as Mac?

I might have to try another char/account.

**Comment by vorghahn** [comment]
08:30:28.699 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
08:30:28.759 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Finished setup for guild *** firing cached events 0
08:30:29.140 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
08:30:29.161 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
08:30:29.163 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
08:30:29.164 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
08:30:29.165 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
08:30:29.197 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
08:30:29.199 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
08:30:29.208 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@569da466
08:30:29.933 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Icecrown
08:30:30.276 [nioEventLoopGroup-2-1] INFO wowchat.game.GameConnector - Connecting to game server Icecrown (51.91.106.148:8092)
08:30:30.651 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerWotLK - Connected! Authenticating...
08:30:31.248 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerWotLK - Successfully logged in!
08:30:31.265 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerWotLK - Warden handling initialized!
08:30:32.008 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerWotLK - Logging in with character ***
08:30:54.374 [JDA RateLimit-Worker 1] DEBUG net.dv8tion.jda.internal.requests.RateLimiter - Removed 4 expired buckets

Tried an older account, got further but still doesnt actual enter the game.  My other account, a disposable one was a week old which seems is still not old enough.
