### ISSUE TITLE
TurtleWoW Hardcore messages

### ISSUE THREAD

**Issue by Lexiebean** [fjaros/wowchat#109]
Turtle WoW now has CHAT_MSG_HARDCORE

WoWChat/src/main/scala/wowchat/game/GamePackets.scala line 46

Any idea how I'd edit this to support it?

**Comment by fjaros** [comment]
Yeah, you'll have to add the new [opcode for the chat event](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/scala/wowchat/game/GamePackets.scala#L45)
I don't know what the opcode is as I don't play turtle wow. You can turn on the [internal packet logging](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/resources/logback.xml#L15) by setting it to DEBUG and then parse the hex codes that wowchat will print to figure out the opcode.

Once you figure it out, you'll need to add it to the ChatEvents, as well as implement it in the "parse" and "valueOf" functions. When that's done, you can create a new section in [chat](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/resources/wowchat.conf#L126) to map this new "hardcore" message as you would Guild or Say.

Then you should be done. One caveat is if the message format is not the same as it is for the Guild/Say case, then you will also need to do some extra work in the [chat message parser](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/scala/wowchat/game/GamePacketHandler.scala#L582) to read it correctly, and again the packet logging will help you figure out the format.

Good luck!

**Comment by welpenhund** [comment]
> Yeah, you'll have to add the new [opcode for the chat event](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/scala/wowchat/game/GamePackets.scala#L45) I don't know what the opcode is as I don't play turtle wow. You can turn on the [internal packet logging](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/resources/logback.xml#L15) by setting the GamePacketDecoder to DEBUG and then parse the hex codes that wowchat will print to figure out the opcode.
> 
> Once you figure it out, you'll need to add it to the ChatEvents, as well as implement it in the "parse" and "valueOf" functions. When that's done, you can create a new section in [chat](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/resources/wowchat.conf#L126) to map this new "hardcore" message as you would Guild or Say.
> 
> Then you should be done. One caveat is if the message format is not the same as it is for the Guild/Say case, then you will also need to do some extra work in the [chat message parser](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/scala/wowchat/game/GamePacketHandler.scala#L582) to read it correctly, and again the packet logging will help you figure out the format.
> 
> Good luck!

How to exactly turn on the packet logger by the config? Or do you have to re-compile the project to enable that?
Thanks in advance.

**Comment by fjaros** [comment]
To turn on the packet logger you don't need to recompile. Set the logging level to DEBUG like I instructed above. Then restart.

**Comment by welpenhund** [comment]
> To turn on the packet logger you don't need to recompile. Set the logging level to DEBUG like I instructed above. Then restart.

Mhhh, that might be difficult on the live server to figure out, right?
https://streamable.com/wk2sdp <-We might have to try it on a PTR cause it would be impossible to figure out the right hex code on the live server? (is there also a way to save the whole debug to somewhere? at least i not found any new created file that includes the whole DEBUG code)

**Comment by fjaros** [comment]
Hmm yeah that's a very fair point.
I just realized that in the handler I have an additional [logger just for chat messages](https://github.com/fjaros/wowchat/blob/5228d7fd355d15b2e02ca1020159dcc37fb4d1cf/src/main/scala/wowchat/game/GamePacketHandler.scala#L563)

So what you can do is in logback.xml, set GamePacketDecoder back to INFO and add the line:
` <logger name="wowchat.game.GamePacketHandler" level="DEBUG" />`
and this should then print only the hex code for any arriving chat messages
