### ISSUE TITLE
Guild Notifications custom channels not working as intended.

### ISSUE THREAD

**Issue by GitGurky** [fjaros/wowchat#110]
I have edited the config to something like the below:
```
guild {
  online {
    enabled=1
    format="`[%user] has come online.`"
    channel=guild-log
  }
  offline {
    enabled=1
    format="`[%user] has gone offline.`"
    channel=guild-log
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
    channel=guild-log
  }
  demoted {
    enabled=1
    format="`[%user] has demoted [%target] to [%rank].`"
    channel=guild-log
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
    channel=guild-log
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
    channel=guild-log
  }
  removed {
    enabled=1
    format="`[%target] has been kicked out of the guild by [%user].`"
    channel=guild-log
  }
  motd {
    enabled=0
    format="`Guild Message of the Day: %message`"
    channel=guild-log
  }
  achievement {
    enabled=0
    format="%user has earned the achievement %achievement!"
    channel=guild-log
  }
}
```

What I noticed is offline is the only one to post in the guild-log channel. So I did a few tests and made it so online was the only one with the custom channel which online then posted in the custom channel, so I added offline as well and what I ended up seeing is offline was the only one to post in the custom channel and online started posting in the guild chat channel.

it seems there is some bug in the code that handled the guild notifs config and only allows 1 of the items to use a custom channel.

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/87ccb320d1a1383b7b088c0acbf36715e19cfa67 . Can you download the latest release zip and try again? Thanks

**Comment by GitGurky** [comment]
yep will build shortly and try it out

**Comment by GitGurky** [comment]
@fjaros that was fast! it works as it should now! Thank you
