### ISSUE TITLE
Help. Newbie. Format massege

### ISSUE THREAD

**Issue by Rorifer** [fjaros/wowchat#119]
Help me figure out how to separate individual messages into separate disord channels
Example:
[Player]: Hello Word!
This message should be output to the "wow_Chat" channel
[Player]: EPGP: +270 GP (slak) for PlayerTwo
This message should be output to the channel "wow_Epgp"
I am using the following code but it is not working. What's my mistake?

`chat {
  channels=[

    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=wow_chat
        format="[%user]: %message"
      }
    }

    {
      direction=wow_to_discord
      wow {
        type=Guild
        format="[%user]: EPGP: %message"
      }
      discord {
        channel=wow_epgp
        format="[%user]: EPGP: %message"
      }
    }
`

**Comment by fjaros** [comment]
Unfortunately that's what format means. All this will do is send the message from Guild to "wow_chat" and to "wow_epgp" with whatever the player said in the place of %message.

What you are looking for is not implemented.

**Comment by Rorifer** [comment]
Понял, спасибо! Решение обошли путем создания Custom channels.
Еще раз Спасибо Вам за прекрасную программу!
Хочу обратить внимание, что при компиляции проекта обнаружено, что проектпо ссылке  (таг)  отличается от комплекта в "коде"
