### ISSUE TITLE
GE_PROMOTION, GE_DEMOTION, GE_REMOVED handling

### ISSUE THREAD

**Issue by elshandra** [fjaros/wowchat#12]
Any chance for handling/forwarding of GE_PROMOTION (0x00 pre Cata) and GE_DEMOTION (0x01 pre cata) events, as well as proper handling of GE_REMOVED (0x05 pre Cata)?

**Comment by fjaros** [comment]
sure i could work on that :) feel free to contribute also.

**Comment by elshandra** [comment]
So, I'm only working with TBC server... And I don't know Scala/Java at all.. But here's what I changed to get it working with TBC (should backport to Vanilla fine, but def not for MoP, Cata)

[WoWChat_Changed.tar.gz](https://github.com/fjaros/wowchat/files/2743690/WoWChat_Changed.tar.gz)

Adds promoted { } and demoted { } keys to guild config, %user = promoter, %target = promotee, %rank = new rank (string).

**Comment by elshandra** [comment]
Yeah I guess I could upload a patch file, I don't want to push it up, because I am pretty sure it will break for future servers (I didn't do any version checking, because for my use case, I don't need to.) It's more just so you can see how the packets need to be interpreted. I have a feeling the values for GE_PROMOTION and GE_DEMOTION may be different for Cata, since they are for the other GE_xx events. I don't have a source for Cata server, so.

**Comment by fjaros** [comment]
it's definitely different for mop & cata. don't worry about that part, i'll implement it.

**Comment by fjaros** [comment]
Support added in https://github.com/fjaros/wowchat/commit/5b0653ab53b4c3204ea6ef43a32ae093b1ace894 and released in v1.2.8

**Comment by elshandra** [comment]
I just had a look at your code, and it's so much better than mine (no surprise). That's why I let you decide on the implementation. The extent of my knowledge of the language is reading your code and making it do what I want, using principles from antiquated languages ;p. Yours looks elegant, thank you sir for taking the time.

Btw, are you supposed to have left that logger.error in @ GamePacketHandlerMoP18414.scala:47 ?

**Comment by fjaros** [comment]
you're welcome! nope, i forgot to delete that part . i was seeing if that packet gets sent automatically or not (it doesn't) . right now that code path never gets executed so i didn't want to bother making another commit. Once I do, i'll just clean that up also.
