### ISSUE TITLE
Bot doesn't join world on Warmane

### ISSUE THREAD

**Issue by EllieSca** [fjaros/wowchat#124]
Starting a couple days ago, bot can no longer login with any character and simply hangs like this:
![image](https://github.com/user-attachments/assets/2975358a-8698-4b76-9478-5ca4b71a3257)

In comparison, on my personal server bot has no troubles logging in:
![image](https://github.com/user-attachments/assets/3cb2608a-b33b-4a9f-800a-0f509340f3f9)

No idea honestly what warmane changed but just letting you know that bot is broken there right now.

**Comment by nerestaren** [comment]
Did you see this @fjaros ?

Thank you ❤️

**Comment by nerestaren** [comment]
Well, whatever Warmane did, they seem to have undone it.

The bot currently works. Did you check it again @EllieSca ?

**Comment by EllieSca** [comment]
Can confirm that bot is back now, closing the issue.
