### ISSUE TITLE
Suggestion: Add config option to sync GMOTD to the latest message in a specific channel (e.g an announcements channel)

### ISSUE THREAD

**Issue by sky1700** [fjaros/wowchat#13]
Basically what the title says, would be a useful addition to the bot, thanks for all of your hard work so far :)

**Comment by fjaros** [comment]
Implemented in https://github.com/fjaros/wowchat/commit/b1fad8cb464d1edea14f7b3f1afbbe456a46d638 . Feel free to download new release zip file!
