### ISSUE TITLE
Add channel ID support for public channels

### ISSUE THREAD

**Issue by fjaros** [fjaros/wowchat#16]
Joining a public channel (general, trade) without the supplied correct channel ID causes unexpected behavior on some servers. While a server side fix is desirable, I still should extract the information from game files and send the appropriate id for these channels.

**Comment by qyh214** [comment]
Indeed, I also had this problem.

**Comment by ForesterDev** [comment]
@fjaros do you have any solution? I have the same problem with global channels. We need a config option to specify channelID for Channel type:

wow {
        type=Channel
        channel="LookingForGroup"
        channelID=26
        format="[%user]: %message"
      }

**Comment by fjaros** [comment]
Haven't really given it much thought as it seems like such a minor issue. Supplying a channel id in the config is not user friendly either. The user won't know what the ID is supposed to be. As far as i know the IDs are contained in each client's dbc files. It would be a big help if one of you could provide me with a list of channel names and their ids for each supported client (1.12.1, 2.4.3, 3.3.5a, 4.3.4, 5.4.8)

**Comment by ForesterDev** [comment]
On TrinityCore, the last changes were - you can connect to global channels only using id, and to custom - only with names. Channel names are different for each locale, but ID are always the same.

3.3.5
```
`ID`,`Name_Lang_enUS`, `Name_Lang_ruRU`
1,"General - %s","Общий: %s" 
2,"Trade - %s","","Торговля: %s"
22,"LocalDefense - %s","Оборона: %s"
23,"WorldDefense","Оборона: глобальный"
25,"GuildRecruitment - %s","Гильдии: %s"
26,"LookingForGroup","Поиск спутников"

```

5.4.8
```
`ID`,`Field04`
1,"Общий: %s"
2,"Торговля: %s"
22,"Оборона: %s"
23,"Оборона: глобальный"
26,"Поиск спутников"

```

7.3.5
```
`ID` `Name`
1,"General - %s"
2,"Trade - %s"
22,"LocalDefense - %s"
26,"LookingForGroup"
27,"BigfootWorldChannel"
28,"MeetingStone"

```

So:

```
`ID`,`Name_enUS`,`Name_ruRU` 
1,"General - %s","Общий: %s" 
2,"Trade - %s","Торговля: %s"
22,"LocalDefense - %s","Оборона: %s"
23,"WorldDefense","Оборона: глобальный"
25,"GuildRecruitment - %s","Гильдии: %s"
26,"LookingForGroup","Поиск спутников"
27,"BigfootWorldChannel","Редкие существа"
28,"MeetingStone","КаменьВстреч"
```

The only proper way to fix this issue - repeat the client behaviour. If you join global channels - always send in packet also the ChannelID besides the ChannelName

**Comment by fjaros** [comment]
Thanks for the ID dump. It totally makes sense from a localization perspective. I do find it a bit strange that all locales join the same channel, just that the title that shows up in their client is different. Since the bot hardcodes enUS as the locale https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/realm/RealmPacketHandler.scala#L51 , I guess I'll just try to lookup the input channel name in a map of name -> id pairs and if it's there, use that one else 0

**Comment by qyh214** [comment]
so,now If I want to in my zhcn client I can edit ahrdcodes enUS to zhCN?

**Comment by ForesterDev** [comment]
> so,now If I want to in my zhcn client I can edit ahrdcodes enUS to zhCN?

Yes, I've done the same for ruRU

**Comment by fjaros** [comment]
What difference does that make? As far as I can tell trinitycore doesn't put you in different channels based on locale?

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/66866c767b1ae80084922bb437134367d8a0ce1d
