### ISSUE TITLE
Cleaner Disconnect Messages

### ISSUE THREAD

**Issue by pogonomic** [fjaros/wowchat#17]
Any chance you could make the "Disconnected from server!" message only show once?

Currently showing like so:
[SYSTEM]: Disconnected from server!
[SYSTEM]: Disconnected from server!
[SYSTEM]: Disconnected from server!
[SYSTEM]: Disconnected from server!

**Comment by fjaros** [comment]
Already fixed by https://github.com/fjaros/wowchat/commit/84ed786ecd9afd321c489ba59e42d972431ebfec. Download latest release file.
