### ISSUE TITLE
Server Shutdown Message

### ISSUE THREAD

**Issue by pogonomic** [fjaros/wowchat#18]
Currently do not see in-game server messages such as:  [SYSTEM]: Server restart in 30 minutes.
But I do see:  [SYSTEM]: Disconnected from server!

Perhaps this is intended behavior?

My config:

  enable_server_motd=0

    {
      direction=wow_to_discord
      wow {
        type=System
      }
      discord {
        channel=guild-chat
        format="[SYSTEM]: %message"
      }
    }

**Comment by fjaros** [comment]
Those messages are SMSG_SERVER_MESSAGE packets which are different than the standard system info chat messages. The bot does not handle those at this time. I will add support for them.

**Comment by pogonomic** [comment]
You rock fjaros!

**Comment by fjaros** [comment]
Feature added in https://github.com/fjaros/wowchat/commit/d54be64d352b4068d0354ac2b9754baa17ad131b
