### ISSUE TITLE
Catch server system arena broadcast messages

### ISSUE THREAD

**Issue by Zoups** [fjaros/wowchat#21]
Hello,

On Netherwing [TBC] there is a new system info that let you know when arena team queue up with arena broadcast messages.
You can enable/disable it with `.character arenaBroadcast`

I want to catch those messages to broadcast them to discord.
I tryed `type=System` but it does not catch the arena broadcast messages.

How can I identify the channel for this messages and catch them in order to redirect them to discord ?

**Comment by fjaros** [comment]
Hmm. well typing .character arenabroadcast certainly works on the bot - system will reply that messages have been enabled/disabled. I don't think i've ever seen an arena broadcast message while playing though. are you sure the bot is getting the messages? i'll need to log one to determine how it arrives to the bot

**Comment by fjaros** [comment]
Can you provide an example of this message? i've never received one.

**Comment by fjaros** [comment]
Actually it turns out it is just a System message and will be handled by "System" setting on bot. However not all characters receive these messages. Your character must first join at least one arena match to start receiving them (even if .character arenabroadcast is enabled). No issue here.
