### ISSUE TITLE
Problem with brackets in wowconf file.

### ISSUE THREAD

**Issue by RAZWANN** [fjaros/wowchat#24]
Back at it again, sorry.. A new problem has risen right now, i can't seem to get the program working due to some syntax errors (i did not fiddle with anything besides filling the info I should). I kept getting this error on several lines of code:
Exception in thread "main" com.typesafe.config.ConfigException$Parse: wowchat.conf: 19: expecting a close parentheses ')' here, not: ']'. 
Found out that just by deleting the square brackets the problem goes away, until this:
Exception in thread "main" com.typesafe.config.ConfigException$Parse: wowchat.conf: 78: expecting a close parentheses ')' here, not: '{'.

I'll leave the entire conf file if this is not enough info.
# Global Discord Configurations
discord {
  token=NTgyOTczOTM2NTg1ODAxNzMy.XO5www.WPAIX7lLSYPYMxGNLMCDf4kV-gM

  enable_dot_commands=1

  # List of server (dot) commands that are explicitly enabled
  # Leaving this as empty means ALL commands are enabled/disabled based on "enable_dot_commands" setting.
  # The commands here should reflect exactly how the command is input in game. Do not prepend the dot character.
  # We can also accept wildcards like "lookup *" or "pinfo *"
  dot_commands_whitelist=0
    #"server info"
    #"lookup *"
  

  # List of Discord channels where commands are enabled. If this is unspecified or empty,
  # ALL channels will have command permissions.
  enable_commands_channels=0 
}
# Global WoW Configurations
wow {
  # You MUST keep this as Mac on Warden (anticheat) enabled servers. Windows Warden is not implemented.
  # Only reason to change this is for servers on which Mac login is not working and also which have Warden disabled.
  platform=Mac

  # Whether to treat server's MotD message as a server SYSTEM message.
  enable_server_motd=1

  version=3.3.5
  realmlist=logon.dalaran-server.com
  realm=Algalon-Main Realm
  account=<>
  password=<>
  character=<>
}

# guild notifications
guild {
  online {
    enabled=1
    format="`[%user] has come online.`"
  }
  offline {
    enabled=1
    format="`[%user] has gone offline.`"
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
  }
  demoted {
    enabled=1
    format="`[%user] has demoted [%target] to [%rank].`"
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
  }
  removed {
    enabled=1
    format="`[%target] has been kicked out of the guild by [%user].`"
  }
  motd {
    enabled=1
    format="`Guild Message of the Day: %message`"
  }
  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"
  }
}
chat {
  channels=general
       {
      direction=wow_to_discord
      wow{
        type=Channel
        channel="global"
        format="[%user]: %message"
             }
    

      }
} 

filters {
  enabled=1
  # patterns are Java Regexes. Google has the answers you seek.
  patterns=[
    ".*(?i)(?=.*g.?ld)(?=.*level)(?=.*item).*$" # case insensitive filter for messages containing all 3 words g?ld, level, and item in any order
    ".*(?=.*>>)(?=.*<<).*$" # filter for messages containg >> and << in any order (both must be in the message)
  
}

Thanks for your support. You are awesome!

**Comment by RAZWANN** [comment]
Figured it out.

**Comment by abdallah-benelmadjat** [comment]
@RAZWANN What was the solution?
