### ISSUE TITLE
Bots don't update player names after rename

### ISSUE THREAD

**Issue by ForesterDev** [fjaros/wowchat#27]
If user change his player name and send something in chat - bots will send message with old name. After rename - server sends opcode SMSG_INVALIDATE_PLAYER to all players in world and clients update information about players. But bots don' handle this packet and don't update other player names without logout

**Comment by fjaros** [comment]
Should be simple to add. I'll work on it

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/b802c748f579906666667c93272b5be9002b5503 . Hopefully it's OK. I did not test it. NOTE: I was unable to find an open source implementation for MoP using this packet. I am hoping it is using the same format as the one from vanilla->cataclysm
