### ISSUE TITLE
Vip channel in system message.

### ISSUE THREAD

**Issue by pennybox** [fjaros/wowchat#28]
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t[VIP]|Hplayer:What|h[What]|h: lol
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t[VIP]|Hplayer:What|h[What]|h: cant quit tho, race in progress
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t[VIP]|Hplayer:What|h[What]|h: OUR race)
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t|Hplayer:Didi|h[Didi]|h: rip
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t|Hplayer:Didi|h[Didi]|h: gonna force close the race
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t|Hplayer:Didi|h[Didi]|h: vanclef u mind fueling me up with som energy so we can test it :3
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t|Hplayer:Didi|h[Didi]|h: ?
[SYSTEM]: [Autobroadcast]: A new command .area has been added. With this you can, for a price, turn an area into an FFA or Sanctuary zone for 2 hours. Time to host your own FFA Events!
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t[VIP]|Hplayer:Brroklyn|h[Brroklyn]|h: asd
[SYSTEM]: |TInterface\ICONS\Achievement_PVP_H_01:23:23:0:-2|t[VIP]|Hplayer:Brroklyn|h[Brroklyn]|h: wtf is this shitt?

**Comment by fjaros** [comment]
Non-issue. Custom message format which the bot doesn't know how to parse. In this case, you will need to make changes to the code directly in Discord#sendMessageFromWow
