### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by merdlin** [fjaros/wowchat#30]
![image](https://user-images.githubusercontent.com/60373652/77344288-b82c3d00-6d11-11ea-9382-38dedec5684c.png)

Could you help me with this problem?

**Comment by fjaros** [comment]
your configuration file has a syntax error.

**Comment by merdlin** [comment]
account=wowchat 

(is this configuration right?)

**Comment by merdlin** [comment]
could you help me with this error? I really liked the bot but I don't know how to solve the error.

**Comment by fjaros** [comment]
you will have to post your config file. you can remove username/password/discord token information.

**Comment by fjaros** [comment]
It will also help if you post the entire error as the first line gives you the exact reason why the configuration fails to be loaded.

**Comment by merdlin** [comment]
![image](https://user-images.githubusercontent.com/60373652/77369011-50d7b280-6d3c-11ea-8158-f8d1b1205ccf.png)

# Global Discord Configurations
discord {
  # Paste the Discord Token below
  # Or set the DISCORD_TOKEN environment variable (this is useful if you want to keep sensitive information out of the config file).
  token=

  enable_dot_commands=1

  # List of server (dot) commands that are explicitly enabled
  # Leaving this as empty means ALL commands are enabled/disabled based on "enable_dot_commands" setting.
  # The commands here should reflect exactly how the command is input in game. Do not prepend the dot character.
  # We can also accept wildcards like "lookup *" or "pinfo *"
  dot_commands_whitelist=[
    #"server info"
    #"lookup *"
  ]

  # List of Discord channels where commands are enabled. If this is unspecified or empty,
  # ALL channels will have command permissions.
  enable_commands_channels=[

  ]

  # If a tag matching fails from Discord when someone @ a non-existent or unmatched person or role,
  # the bot will whisper back notifying so.
  enable_tag_failed_notifications=1
}

# Global WoW Configurations
wow {
  # You MUST keep this as Mac on Warden (anticheat) enabled servers. Windows Warden is not implemented.
  # Only reason to change this is for servers on which Mac login is not working and also which have Warden disabled.
  platform=Mac

  # Whether to treat server's MotD message as a server SYSTEM message.
  enable_server_motd=1

  version=3.3.5
  realmlist=51.79.6.75
  realm=Mythic WoW 3.3.5a
  account=<>
  password=<>
  character=<Wowchat>

# Other example configurations

# version=1.12.1
# realmlist=logon.lightshope.org
# realm=Northdale
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=2.4.3
# realmlist=logon.vengeancewow.com
# realm=stonetalon
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=3.3.5
# realmlist=wow.gamer-district.org
# realm=Echoes 1x
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=4.3.4
# realmlist=login.hades-wow.com
# realm=hades
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=5.4.8
# realmlist=hu.logon.tauri.hu
# realm="[en] evermoon"
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>
}

# guild notifications
guild {
  online {
    enabled=0
    format="`[%user] has come online.`"
  }
  offline {
    enabled=0
    format="`[%user] has gone offline.`"
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
  }
  demoted {
    enabled=1
    format="`[%user] has demoted [%target] to [%rank].`"
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
  }
  removed {
    enabled=1
    format="`[%target] has been kicked out of the guild by [%user].`"
  }
  motd {
    enabled=1
    format="`Guild Message of the Day: %message`"
  }
  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"
  }
}

# chat to redirect
chat {
  channels=[
    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Officer
        format="[%user]: %message"
      }
      discord {
        channel=officer-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Say
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Yell
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Emote
        format="%user %message"
      }
      discord {
        channel=guild-chat
        format="%user %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=System
      }
      discord {
        channel=guild-chat
        format="[SYSTEM]: %message"
      }
    }

    # Custom channels
    {
      direction=wow_to_discord
      wow {
        type=Channel
        channel="General - Orgrimmar"
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%target] [%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Channel
        channel="Trade - City"
        format="[%user]: %message"
      }
      discord {
        channel=trade-chat
        format="[%target] [%user]: %message"
      }
    }

    # Class channels
    {
      direction=both
      wow {
        type=Channel
        channel=Cast
        format="[%user]: %message"
      }
      discord {
        channel=mages
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Channel
        channel=Chadwarriors
        format="[%user]: %message"
      }
      discord {
        channel=warriors
        format="[%user]: %message"
      }
    }
  ]
}

filters {
  enabled=0
  # patterns are Java Regexes. Google has the answers you seek.
  patterns=[
    ".*(?i)(?=.*g.?ld)(?=.*level)(?=.*item).*$" # case insensitive filter for messages containing all 3 words g?ld, level, and item in any order
    ".*(?=.*>>)(?=.*<<).*$" # filter for messages containg >> and << in any order (both must be in the message)
  ]
}

**Comment by merdlin** [comment]
# Global Discord Configurations
discord {
  # Paste the Discord Token below
  # Or set the DISCORD_TOKEN environment variable (this is useful if you want to keep sensitive information out of the config file).
  token=

  enable_dot_commands=1

  # List of server (dot) commands that are explicitly enabled
  # Leaving this as empty means ALL commands are enabled/disabled based on "enable_dot_commands" setting.
  # The commands here should reflect exactly how the command is input in game. Do not prepend the dot character.
  # We can also accept wildcards like "lookup *" or "pinfo *"
  dot_commands_whitelist=[
    #"server info"
    #"lookup *"
  ]

  # List of Discord channels where commands are enabled. If this is unspecified or empty,
  # ALL channels will have command permissions.
  enable_commands_channels=[

  ]

  # If a tag matching fails from Discord when someone @ a non-existent or unmatched person or role,
  # the bot will whisper back notifying so.
  enable_tag_failed_notifications=1
}

# Global WoW Configurations
wow {
  # You MUST keep this as Mac on Warden (anticheat) enabled servers. Windows Warden is not implemented.
  # Only reason to change this is for servers on which Mac login is not working and also which have Warden disabled.
  platform=Mac

  # Whether to treat server's MotD message as a server SYSTEM message.
  enable_server_motd=1

  version=3.3.5
  realmlist=51.79.6.75
  realm=Mythic WoW 3.3.5a
  account=<>
  password=<>
  character=<Wowchat>

# Other example configurations

# version=1.12.1
# realmlist=logon.lightshope.org
# realm=Northdale
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=2.4.3
# realmlist=logon.vengeancewow.com
# realm=stonetalon
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=3.3.5
# realmlist=wow.gamer-district.org
# realm=Echoes 1x
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=4.3.4
# realmlist=login.hades-wow.com
# realm=hades
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>

# version=5.4.8
# realmlist=hu.logon.tauri.hu
# realm="[en] evermoon"
# account=<discord bot account>
# password=<discord bot password>
# character=<in game character>
}

# guild notifications
guild {
  online {
    enabled=0
    format="`[%user] has come online.`"
  }
  offline {
    enabled=0
    format="`[%user] has gone offline.`"
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
  }
  demoted {
    enabled=1
    format="`[%user] has demoted [%target] to [%rank].`"
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
  }
  removed {
    enabled=1
    format="`[%target] has been kicked out of the guild by [%user].`"
  }
  motd {
    enabled=1
    format="`Guild Message of the Day: %message`"
  }
  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"
  }
}

# chat to redirect
chat {
  channels=[
    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Officer
        format="[%user]: %message"
      }
      discord {
        channel=officer-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Say
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Yell
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Emote
        format="%user %message"
      }
      discord {
        channel=guild-chat
        format="%user %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=System
      }
      discord {
        channel=guild-chat
        format="[SYSTEM]: %message"
      }
    }

    # Custom channels
    {
      direction=wow_to_discord
      wow {
        type=Channel
        channel="General - Orgrimmar"
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%target] [%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=Channel
        channel="Trade - City"
        format="[%user]: %message"
      }
      discord {
        channel=trade-chat
        format="[%target] [%user]: %message"
      }
    }

    # Class channels
    {
      direction=both
      wow {
        type=Channel
        channel=Cast
        format="[%user]: %message"
      }
      discord {
        channel=mages
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Channel
        channel=Chadwarriors
        format="[%user]: %message"
      }
      discord {
        channel=warriors
        format="[%user]: %message"
      }
    }
  ]
}

filters {
  enabled=0
  # patterns are Java Regexes. Google has the answers you seek.
  patterns=[
    ".*(?i)(?=.*g.?ld)(?=.*level)(?=.*item).*$" # case insensitive filter for messages containing all 3 words g?ld, level, and item in any order
    ".*(?=.*>>)(?=.*<<).*$" # filter for messages containg >> and << in any order (both must be in the message)
  ]
}

**Comment by fjaros** [comment]
as the error says, you have an @ outside of quotes. i am guessing either your account or password contains a "@" characters. in this case please put "quotes" around your account and/or password
