### ISSUE TITLE
Twinstar Ads

### ISSUE THREAD

**Issue by xParad0x** [fjaros/wowchat#32]
Not sure if this is the right place but cant you change twinstar resolver to wowhead?

**Comment by fjaros** [comment]
You can change them to whatever you like by changing linkSite string(s) in https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/discord/MessageResolver.scala

I am not affiliated with Twinstar in any way. They just seemed to be the most reliable databases during development of this project. If you have a better suggestion, I can change the links as well.

**Comment by disclosurez** [comment]
anyway to make this a config option, to set the database in config?
Or any help appreciated on getting this rebuilt with a different database

**Comment by xParad0x** [comment]
The reason why i even asked this is to find out if twinstar was an affiliate here.
If you want to change link resolves just download the source code are build it yourself using scala.... Its very easy if you have java knowledge
