### ISSUE TITLE
Discord Bot Status

### ISSUE THREAD

**Issue by Astrono1293** [fjaros/wowchat#42]
How would I go about changing the Status of the Discord Bot, right now it shows "Watching # Guildies Online" 

I want to change to "Playing Game" or anything apart from original one?

Thank you

**Comment by fjaros** [comment]
Impossible to do via config but the code that handles is in https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/discord/Discord.scala#L32 . You can change the places where this is called or comment them out and call changeStatus to change the message to whatever you want

**Comment by Astrono1293** [comment]
can you provide an example of a code? im not very familiar with scala but i compile my own so i can do the changes. Thank you

**Comment by Astrono1293** [comment]
never mind i figured it out

**Comment by Willozwisp** [comment]
How can I change the display language from English to Russian?
