### ISSUE TITLE
A help / suggestion to improve this great work.

### ISSUE THREAD

**Issue by RaggaHC** [fjaros/wowchat#43]
The idea to expand the great utility of this tool is to also add the Warcraft 3 Servers, here I leave how to insert a pvpgn chat for example from an html:

**from your website:**

[chat.txt](https://github.com/fjaros/wowchat/files/5394922/chat.txt)
chat.txt >> chat.html

**Here I leave the complete information:**

[https://github.com/reillychase/pvpgn-html5-chat-client](url)

**I sincerely hope this helps you because what you did was a great job, you left me in love with your chat, you are the best.
Remember that WarCraft 3, Starcraft and Diablo 2 are pvgn Chat, and it works with an IP and a default chat port which is 6112..**

**Comment by RaggaHC** [comment]
this occurs by putting this data:
http://prntscr.com/v0yv76
and connect:
http://prntscr.com/v0yuq2

**Comment by fjaros** [comment]
This is out of scope for this project.
