### ISSUE TITLE
Stuck on Connected Websocket

### ISSUE THREAD

**Issue by AkbarSubastian** [fjaros/wowchat#45]
Hi,
i got stuck on Connected to Websocket, the bot connected to discord but didnt log to game.
your great wowchat code works before, im playing on warmane private server.

please help

**Comment by fjaros** [comment]
if you report a bug at least provide a screenshot of the program window.

**Comment by Shulishin** [comment]
![image](https://user-images.githubusercontent.com/52592322/97375280-8c5be000-190e-11eb-9117-e6eb50b9f00d.png)
Hi fjaros,

Here's a screen shot. Was working fine until the character went offline while the discord bot was fine. As you can see it logs into discord, but doesn't go any further to connect to WoW.

**Comment by fjaros** [comment]
thanks. looks like this is a Discord-side issue. need to investigate.

**Comment by fjaros** [comment]
Fixed by updating to new Discord connection library in https://github.com/fjaros/wowchat/commit/c61721b28d69d75b927d6439b6fdb76bf8daec2e . New release provided: https://github.com/fjaros/wowchat/releases/tag/1.3.4

**Comment by Yatzii93** [comment]
Thanks for the update!
