### ISSUE TITLE
user tagging via @name from game chat to discord is not working

### ISSUE THREAD

**Issue by siadrian** [fjaros/wowchat#47]
I have the bot sending guild and officer chat to two discord text channels and before the update sending any @name would ping that person. Right now that doesn't work but @role does.

I can see from the console that any @name is sent as a string but @role is sent as @<role_id>.

**Comment by fjaros** [comment]
yep i'm sure it's a side effect of updating the discord library. i'll take a look

**Comment by fjaros** [comment]
Fixed by https://github.com/fjaros/wowchat/commit/321571c410cc37c71220aec91d06eeca7c8b449a

**Comment by siadrian** [comment]
I'm testing it right now

**Comment by siadrian** [comment]
@fjaros 
I'm not sure this is working properly. I've updated the bot on my server, started it and also enabled both presence and server members intents.

Here's the current behavior:
- Sending messages from discord are not seen in wow. I've checked the bot logs and there's no error or message.
- ?who and ?online commands not working but the bot says "Watching x guildies online"
- Sending messages from the game works but tagging is still not working

**Comment by fjaros** [comment]
i forgot to add message intent :( Fixed -> https://github.com/fjaros/wowchat/commit/22911daede5e0a473d7c249b25393e3043e7b421

**Comment by siadrian** [comment]
Alright, I'll test it now

**Comment by fjaros** [comment]
It is on git. redownload the release

**Comment by siadrian** [comment]
the release is from 1 hour ago, there's one commit above it

**Comment by siadrian** [comment]
I pulled the latest changes and built it. Communication is again bi-directional but the tagging still doesn't work.

**Comment by siadrian** [comment]
This is strange, it doesn't resolve all tags. I've tried it one 4 people, including myself, and the tagging worked only for one of them.

**Comment by fjaros** [comment]
yeah that's my downfall of only testing it on a server of size 2. i've tested it on a larger server... even with the presences intent, the only members that the Discord API returns is the bot and the main admin of the discord server, nobody else. not quite sure how to fix this to be honest. will have to play with the library more when time allows

**Comment by fjaros** [comment]
Actually looks like https://github.com/fjaros/wowchat/commit/2a9d50708f47845d4fd4162f3604d2b022fe5c0b should do the trick.

**Comment by siadrian** [comment]
I've tested it with your latest changes:

- Communication is bi-directional
- Tagging people in discord, from the game, works. Discord user ids can be seen in the console

Fixed
