### ISSUE TITLE
 enable_commands_channels does not work

### ISSUE THREAD

**Issue by disclosurez** [fjaros/wowchat#49]
Hey,

The config entry
`
 enable_commands_channels=`
is not working.

my config:
` enable_commands_channels=[commands]`

So, in theory only the discord channel called "commands" should send allow messages to be sent ingame.

But, this appears not to be the case, if a player sends a "command" (e.g. .server info ) to another channel synced with discord, the output also works.

Obviously, this is then a security issue if you are expecting commands to only work from a specific channel only

**Comment by fjaros** [comment]
Bot commands and dot commands are not the same.

enable_commands_channels only applies towards bot commands - ?who and ?gmotd
If you use a dot command directly, the server returns a regular system message like with .server info . The bot cannot distinguish this message from any other System message so it will paste it to whichever channels you configured to post System messages.
