### ISSUE TITLE
?who command

### ISSUE THREAD

**Issue by entryb** [fjaros/wowchat#52]
Is there a way to have the command return general online players like in the /who command in-game instead of guild members? Also are there any other ?commands that could be used in general, couldnt find any documentation other than dot commands though

**Comment by fjaros** [comment]
you can use "?who <name>" to query for names containing the parameter. without the parameter, it will query guild members only.
there is also ?gmotd as another command. you can look at https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/commands/CommandHandler.scala if you'd like to implement more.
