### ISSUE TITLE
Was working fine but suddenly stopped working

### ISSUE THREAD

**Issue by mdlsvensson** [fjaros/wowchat#53]
Hey. Thanks for creating this wonderful bot. My instance was working fine for many days, but now it isn't registering any messages, be it in-game or in discord.

I did not change any settings from it working. I went on the discord character and checked that it could write in guild, and it did.

My config
[wowchat.txt](https://github.com/fjaros/wowchat/files/5899205/wowchat.txt)

**Comment by fjaros** [comment]
whitemane works with the bot. not really sure what to tell you other than discord tends to desync in rare cases and you might just have to restart the bot.
