### ISSUE TITLE
Bot does not connect to wow if the build version in DB realmlist table is changed 

### ISSUE THREAD

**Issue by AlastorStrixEfuartus** [fjaros/wowchat#55]
Bot works fine but I changed the build version of the WOTLK wow server im running from 12340 to 12341 and since then bot cannot connect to it even when in config there is clearly mentioned its still 3.3.5 I guess there is some internal build check that causes it to not connect even when it should just use wotlk packet parsing and run without problem

**Comment by fjaros** [comment]
Have you tried setting build=12341 in the config? Read the readme.

**Comment by AlastorStrixEfuartus** [comment]
Ah thanks I was not aware that there is option to set build in config since it was not mentioned in examples in the wowchat.conf file itself I just assumed that readme contains same data as the config didnt knew there was param build 
thanks once more
