### ISSUE TITLE
WARDEN ON WINDOWS IS NOT SUPPORTED!

### ISSUE THREAD

**Issue by Willozwisp** [fjaros/wowchat#56]
WARDEN ON WINDOWS IS NOT SUPPORTED! BOT WILL SOON DISCONNECT! TRY TO USE PLATFORM MAC! 

Bot sometimes disconected. But when i use Mac, bot not connected. How Fix It?

**Comment by fjaros** [comment]
What problem do you have when using Mac? Can you share the server you are connecting to?

**Comment by Willozwisp** [comment]
Failed to login! Error code: 0E (wowcircle.net)

**Comment by fjaros** [comment]
Can you try downloading the latest release zip from https://github.com/fjaros/wowchat/releases ?  Even if you have the same version number, this zip contains a fix you don't have.

**Comment by Willozwisp** [comment]
Ok. I try it. Report after..

**Comment by Willozwisp** [comment]
No. Not worked.

**Comment by fjaros** [comment]
then share configuration - version, realmlist, realm

**Comment by Willozwisp** [comment]
version=3.3.5
realmlist=logon.wowcircle.me
realm=WoW Circle 3.3.5a x5 (WoW Circle 3.3.5a x1 same)

**Comment by fjaros** [comment]
i see. yes it looks like this server is blocking mac logins and has enabled warden. in this case the bot will not work on that server at this time.

**Comment by Willozwisp** [comment]
Can this be fixed in the future?

**Comment by HuluCder** [comment]
Pls, @fjaros, fix this 😭

**Comment by fjaros** [comment]
Just to be clear - this is not a bug. Supporting warden correctly is very difficult for a number of reasons and pretty much impossible on sophisticated servers like warmane. At the very least, the bot would need to:
A) Be tied to running only on Windows
B) Be able to load WoW and scan WoW's memory space (Warden mem/page check)
C) Be able to parse & execute WoW's addon code (Warden Lua check)

I have no intention of hacking WoW or trying to figure out each private server's implementation to enable support for any of these. It is a high-effort, multi-month project.

Your best bet would be to convince the administrators of these servers to allow the bot to function or to provide you with an alternative way to read the chat messages & send them to Discord.

**Comment by Willozwisp** [comment]
TY.
