### ISSUE TITLE
[NOT WORKING] Login failed. Wait a moment and try again!

### ISSUE THREAD

**Issue by n4ndo** [fjaros/wowchat#57]
Hello,

Today stop working as previous days wowchat:

![image](https://user-images.githubusercontent.com/820868/119038672-fdc9b180-b978-11eb-98a0-a13cf2e168d6.png)

Like you can see, wowchat connect correctly, but then, cannot continue after findind the realm, i re check all the information, nothing changed from serverside or wowchat side.

The weird thing that i saw is that appear this:  w.r.RealmPacketHandlerTBC, and this is a WOTLK realm (AzerothCore)

What can i do?

Thank you very much.

**Comment by fjaros** [comment]
```
15:43:13.155 INFO  w.r.RealmPacketEncoder - SEND REALM PACKET: 0000 - ...
15:43:13.271 INFO  w.r.RealmPacketDecoder - RECV REALM PACKET: 0000 - ...
15:43:13.281 INFO  w.r.RealmPacketEncoder - SEND REALM PACKET: 0001 - 01 B0 5F 72 F3 FB 07 06 EB 7B F4 41 99 56 EC EA 39 23 EC F1 61 1B 0A 01 B7 B8 24 3B D3 E3 B7 3E 6F C4 4D 7D CF 1C DC 83 04 97 E7 D5 C4 90 13 42 FF 9D 47 15 B8 2C 5D 92 E1 B8 CC 37 C2 25 C8 07 C6 9B 10 C0 FB 71 2B 26 00 00
15:43:13.354 INFO  w.r.RealmPacketDecoder - RECV REALM PACKET: 0001 - 00 98 08 A8 BF E2 E3 14 A7 17 24 B4 26 64 3F DE 92 E7 AC 99 80 00 00 80 00 00 00 00 00 00 00
15:43:13.354 INFO  w.r.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Lord King of Chaos
15:43:13.354 INFO  w.r.RealmPacketEncoder - SEND REALM PACKET: 0010 - 00 00 00 00
15:43:13.424 INFO  w.r.RealmPacketDecoder - RECV REALM PACKET: 0001 - 04 03 00
15:43:13.425 ERROR w.r.RealmPacketHandlerTBC - Login failed. Wait a moment and try again!
15:43:13.433 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...
```
it looks like asking for realm list causes this server to return logon proof packet with an error code. Even though the packet (0001) was already returned previously as a successful one.

I can fix it by implementing some login state variable in the bot but makes me feel interested in what kind of spaghetti code this server is using :)

**Comment by n4ndo** [comment]
Hey @fjaros thanks for your  answer.

Weird, the last thing the implement was totp, but that was already implemented on TrinityCore and was working correctly.

Thanks for your support and this amazing tool, please let me know if i can help you in some way.

**Comment by fjaros** [comment]
It is a server issue.  Authserver should not be sending packet 0x01 twice. Workaround: https://github.com/fjaros/wowchat/commit/17de68d5e55148f882383c26833030b92e495860 . Feel free to download the release at https://github.com/fjaros/wowchat/releases . I just updated the zip.
