### ISSUE TITLE
Unable to access jarfile wowchat.jar on linux

### ISSUE THREAD

**Issue by jagehring** [fjaros/wowchat#58]
I downloaded the newest release and when I run the run.sh file and get that error.

**Comment by fjaros** [comment]
yeah that's a permissions issue. make sure the java binary on your system is chmod +x and the directory path of wowchat.jar also has +x. the jar needs to have at least +r

**Comment by jagehring** [comment]
Don't see wowchat.jar file

**Comment by fjaros** [comment]
not quite sure what to tell you then. make sure you download the correct file (the zip file) - https://github.com/fjaros/wowchat/releases/download/v1.3.7/wowchat-1.3.7.zip 

Use unzip to extract it and it will contain file called wowchat.jar. Once you finish editing the config, all you need is: ```chmod +x run.sh && ./run.sh```
provided you have java installed.
If you are struggling using the release directly, you can always compile everything from source. Per readme:
```OR to compile yourself:

WoW Chat is written in Scala and compiles to a Java executable using maven.
It uses Java JDK 1.8 and Scala 2.12.12.
Run mvn clean package which will produce a file in the target folder called wowchat-1.3.7.zip
unzip wowchat-1.3.7.zip, edit the configuration file and run java -jar wowchat.jar <config file>
If no config file is supplied, the bot will try to use wowchat.conf```
