### ISSUE TITLE
enhancement : multiple character to support multiple guild

### ISSUE THREAD

**Issue by firelook** [fjaros/wowchat#61]
Today we can see the activity of  the system through the eye of one character who belongs for example to 1 guild
=> if we have several guild, and enhace the tool to match all of them we will have a repetition of system events

the only way is to have the hability to have a "table"  to have as many wow connection as guild
=> with that only 1 system event
=> we have wee have the log of all events to the guild link to one character

**Comment by fjaros** [comment]
if you're logging on multiple characters, it would imply you have multiple instances of wowchat running.
then, why not just relay system events from one character, and the other relay guild events only?

**Comment by firelook** [comment]
yes it is a good idea
