### ISSUE TITLE
Suggestion: Add config option for possibility specify allowed channels for ?who/?online commands

### ISSUE THREAD

**Issue by ForesterDev** [fjaros/wowchat#7]
Current behaviour: I can type in discord at any channel ?who / ?online and bot will sends me answer in that channel

Suggestion: i can specify in config channel name (or few names with comma), where bot can process this commands and sends answer. If empty - bot will process ? commands in any channels

**Comment by fjaros** [comment]
Sure. I can add a config option for each channel whether or not to allow commands. Also, there are many possibilities to make commands other than ?who . If you feel something is very useful, please suggest it.
