### ISSUE TITLE
Cannot get commands working in discord

### ISSUE THREAD

**Issue by wtfcolt** [fjaros/wowchat#70]
It seemed fine a few weeks ago, but I set up a bot on a new server and I'm having troubles.

 Guild/officer chat seems to work fine. However most "channels" and bot commands are not working. 
 
- The proper ID is set in the config and there's no errors. Just nothing happens. 
- I logged into the discord character to verify it could send server commands and that seems okay.  
- The 'everyone' role on discord has send/read message permissions on the channel, and the bots role has no special permissions itself, so it should be seeing the messages. 

 I was able to temporarily get the bot to join the trade and world channels in my config by logging onto that account manually then joining the channels, but that only seemed to work until i restarted the bot once. The bot does join the channels, it says 'Discord has joined world' when I'm on another character in that channel.

3.3.5a
cmangos
bot v1.3.8
bot sitting in ironforge

[config.txt](https://github.com/fjaros/wowchat/files/8218997/config.txt)

**Comment by JoPeAlmeida** [comment]
try removing the "" in the channel from wow section
type=Channel
channel=world

**Comment by wtfcolt** [comment]
That seems to work to fix the channels, thanks! Still can't get commands to work for some reason.

**Comment by JoPeAlmeida** [comment]
enable_dot_commands=1 should be zero no?
 i always confuse, but i think 1 is FALSE, 0 is TRUE :D

**Comment by fjaros** [comment]
Thanks for helping out @JoPeAlmeida ! Also remove the "" in the enable_commands_channels section

**Comment by wtfcolt** [comment]
Thank you both for the replies. I've changed the ID to the channel name and removed the quotes, and tried switching enable_dot_commands, but I'm still not having any luck.

**Comment by LuisEduLeiva** [comment]
did u fix it?
