### ISSUE TITLE
Private messages

### ISSUE THREAD

**Issue by HuluCder** [fjaros/wowchat#71]
Is it possible to implement the ability to write to private messages from a bot?

**Comment by fjaros** [comment]
You would need to configure a discord -> wow chat with type=Whisper and channel=Name of person to whisper to
The name is static so it would always whisper a single person.

**Comment by Makcumoz** [comment]
> Вам нужно будет настроить discord -> wow chat с type=Whisper и channel=Имя человека, чтобы шептать имя статично, чтобы оно всегда шепталось одному человеку.



> You would need to configure a discord -> wow chat with type=Whisper and channel=Name of person to whisper to The name is static so it would always whisper a single person.

Not work "channel=Name of person" pm not work :(
