### ISSUE TITLE
new line in command ?who

### ISSUE THREAD

**Issue by PentSec** [fjaros/wowchat#76]
Hello mate,

how i can add a little new line per character online when i put "?who"  like that

Elves (85 Shaman in Unknown Zone),
Srbinlol (85 Paladin in Nagrand),
Terr (85 Shaman in Hyjal),
Wackycow (85 Paladin in Nagrand)

btw, amazing project.

**Comment by fjaros** [comment]
In https://github.com/fjaros/wowchat/blob/7ffc62e0fd343d570549b2f375b174778c23f541/src/main/scala/wowchat/game/GamePacketHandler.scala#L110
you will want to change
`.mkString(getGuildiesOnlineMessage(false), ", ", "")`
to
`.mkString(getGuildiesOnlineMessage(false), ",\n", "")`

**Comment by PentSec** [comment]
amazing.

I am very new to this scala and I am learning a little with your code.

thanks for your answer.
Solved

**Comment by fjaros** [comment]
don't waste your time on scala. pretty dead language unfortunately :)

**Comment by PentSec** [comment]
ya but, it would be very difficult to convert this code to another language for me.
