### ISSUE TITLE
Works on Windows, doesnt Linux 10 (buster)

### ISSUE THREAD

**Issue by EetuTseng** [fjaros/wowchat#78]
Hello!

Just updated to v1.3.8 and set up a new server running Linux 10 (buster).
Set up as on previous server.

Running run.sh stops at "INFO wowchat.WoWChat$ - Connecting to Discord..." with no further response.
Running run.bat at my local machine with the same wowchat.conf works just fine.

Any ideas why?
Thanks in advance.

Regards.

**Comment by EetuTseng** [comment]
Worked after switching from Java 17 to Java 8.

Most likely my fault.
Thanks.

**Comment by fjaros** [comment]
Weird. I don't see why it wouldn't work on newer Java versions. It would help to get a log turned on DEBUG to see if it's something happening in the discord library or somewhere else.
