### ISSUE TITLE
ignore default message by server

### ISSUE THREAD

**Issue by PentSec** [fjaros/wowchat#79]
Hello there,.. again 
How could I ignore a default message from the server when the character connects.
and contain these words like that "Vote for the server always"

i think can i add this here. 

https://github.com/fjaros/wowchat/blob/7ffc62e0fd343d570549b2f375b174778c23f541/src/main/scala/wowchat/game/GamePacketHandlerWotLK.scala#L131

But maybe you can help me think a little.
thanks again for replying.

**Comment by fjaros** [comment]
you could also leverage the filters feature in config

**Comment by PentSec** [comment]
I don't know how the filters work. 
I don't know what I'm doing wrong but it's not working for me :(

![image](https://user-images.githubusercontent.com/11955573/170394644-0d63ef31-a70b-4583-80b6-07d701a35e83.png)

![image](https://user-images.githubusercontent.com/11955573/170394728-37a591d1-262f-484b-9aa5-daa7efc09a57.png)

keep sending the message to discord :(

**Comment by PentSec** [comment]
I don't know how many times I've read the code. and I had not seen the option of filters xD
Sorry thanks for replying again.

**Comment by fjaros** [comment]
for some reason you missed the obvious choice which was to literally copy the message as is.... 
"SYSTEM: Your voting buff ran out, please vote on the website to regain it."
