### ISSUE TITLE
Core Version + Races = "unknown"

### ISSUE THREAD

**Issue by angrytoilet** [fjaros/wowchat#80]
The system is showing "unknown" for any races above the version available.  
If there is a place to edit this, or, if a solution is to up the version this would be fine.
I would also assume that any custom races / class would have issues as well.

**Comment by fjaros** [comment]
Not sure exactly what you're asking. The bot has the correct races and classes defined for vanilla and up to mists of pandaria. If you are running the bot on some custom server which has added races/classes or redefined those mappings for whatever reason then it would make sense they would be wrong or show "Unknown".
If this is the case, you will need to change/add mappings in the code https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GamePackets.scala#L106 .
And then recompile the bot (instructions at the end of README)
