### ISSUE TITLE
commands like ?who from discord doesn't work

### ISSUE THREAD

**Issue by Annyelicious** [fjaros/wowchat#83]
Hi everyone

I move recently my vps hosting from google cloud platform to racknerd.
I can run the discord bot on the new host, i can read and send messages from discord to wow and wow to discord, but i can run commands from discord, especially ?who (to know who is online)

In the previous hosting everything worked correctly, now, I don't know what is happening that when I write ?who, it appears as a message on the other side (wow guild chat) but the command does not work.

Maybe it's something related to the new hosting? It's the only thing that changed.

And by the way, I don't know if it's because of the hosting region, but it takes a long time to connect the wow account. (misblade, pandaria)

Any ideas?

**Comment by LuisEduLeiva** [comment]
<img width="1199" alt="Screen Shot 2022-07-30 at 12 54 33" src="https://user-images.githubusercontent.com/53169828/181933800-377cb2ab-7106-442d-9615-d15dc7f4f99a.png">

Should I move something in the vps configuration maybe?

**Comment by fjaros** [comment]
This has nothing to do with your vps settings. Did you by any chance put something in `enable_commands_channels` ?

**Comment by LuisEduLeiva** [comment]
`
  # List of Discord channels where commands are enabled. If this is unspecified or empty,
  # ALL channels will have command permissions.
  enable_commands_channels=[
    "mop-game-gchat"
    "mop-game-officer"
  ]
`

**Comment by fjaros** [comment]
Can you try with just leaving that field blank? As In:
```enable_commands_channels=[]```

**Comment by LuisEduLeiva** [comment]
![WoWScrnShot_080122_222025](https://user-images.githubusercontent.com/53169828/182277920-c57e2c26-fc77-4487-b8cb-d9a7c8bebf59.jpg)

**Comment by LuisEduLeiva** [comment]
<img width="314" alt="Screen Shot 2022-08-01 at 22 22 36" src="https://user-images.githubusercontent.com/53169828/182278023-d296880f-13a8-4784-8e14-fa8bd8729b0e.png">

**Comment by LuisEduLeiva** [comment]
<img width="923" alt="Screen Shot 2022-08-01 at 22 23 31" src="https://user-images.githubusercontent.com/53169828/182278114-7d024e27-e19e-4336-9bd0-a516a385e241.png">

**Comment by LuisEduLeiva** [comment]
Any idea about why the prefix doesn't work?
