### ISSUE TITLE
Cannot write messages from discord to guild or channel

### ISSUE THREAD

**Issue by dkapte** [fjaros/wowchat#86]
I have successfully setup the bot to read the guild chat + world channel and post it in the discord channel. The only issue i have is that i cannot send any chats from discord to the guild chat or to the channel. Could you please help out why. The BOT has all premissions in the discord channel

This is my config (sorry about the format)

`
enable_dot_commands=0
dot_commands_whitelist=[]
enable_commands_channels=[]
enable_tag_failed_notifications=1
`

guild {
  online {
    enabled=1
    format="`[%user] has come online.`"
  }
  offline {
    enabled=0
    format="`[%user] has gone offline.`"
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
  }
  demoted {
    enabled=1
    format="`[%user] has demoted [%target] to [%rank].`"
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
  }
  removed {
    enabled=1
    format="`[%target] has been kicked out of the guild by [%user].`"
  }
  motd {
    enabled=0
    format="`Guild Message of the Day: %message`"
  }
  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"
  }
}

chat {
  channels=[
    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=1054854028229611111
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Officer
        format="[%user]: %message"
      }
      discord {
        channel=1054854028229611111
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Say
        format="[%user]: %message"
      }
      discord {
        channel=1054854028229611111
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Yell
        format="[%user]: %message"
      }
      discord {
        channel=1054854028229611111
        format="[%user]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Emote
        format="%user %message"
      }
      discord {
        channel=1054854028229611111
        format="%user %message"
      }
    }
    {
      direction=both
      wow {
        type=System
      }
      discord {
        channel=1054854028229611111
        format="[SYSTEM]: %message"
      }
    }

    {
      direction=both
      wow {
        type=Channel
        channel="Wereldchat"
        format="[%user]: %message"
      }
      discord {
        channel=1054854028229611111
        format="[%target] [%user]: %message"
      }
    }
  ]
}

filters {
  enabled=0
  patterns=[
    ".*(?i)(?=.*g.?ld)(?=.*level)(?=.*item).*$" # case insensitive filter for messages containing all 3 words g?ld, level, and item in any order
    ".*(?=.*>>)(?=.*<<).*$" # filter for messages containg >> and << in any order (both must be in the message)
  ]
}

>

**Comment by fjaros** [comment]
Config seems to be good. Is it possible the server you are on has some level restrictions where players cannot talk until they are a certain level? This could be the case.

**Comment by dkapte** [comment]
I boosted the discord bot to level 80 and tested it ingame and can send messages without any problem in the world channel and guild so tested it and no problem ingame. Only through discord it does not seem to come through from discord to wow. Only from wow to discord although i set the config to direction=both

**Comment by pnetrio** [comment]
Hello i have same issue now on Stormforge PTR

# Global Discord Configurations
discord {
  # Paste the Discord Token below
  # Or set the DISCORD_TOKEN environment variable (this is useful if you want to keep sensitive information out of the config file).
  token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  enable_dot_commands=1

  # List of server (dot) commands that are explicitly enabled
  # Leaving this as empty means ALL commands are enabled/disabled based on "enable_dot_commands" setting.
  # The commands here should reflect exactly how the command is input in game. Do not prepend the dot character.
  # We can also accept wildcards like "lookup *" or "pinfo *"
  dot_commands_whitelist=[
    #"server info"
    #"lookup *"
  ]

  # List of Discord channels where commands are enabled. If this is unspecified or empty,
  # ALL channels will have command permissions.
  enable_commands_channels=[

  ]

  # If a tag matching fails from Discord when someone @ a non-existent or unmatched person or role,
  # the bot will whisper back notifying so.
  enable_tag_failed_notifications=1
}

# Global WoW Configurations
wow {
  # You MUST keep this as Mac on Warden (anticheat) enabled servers. Windows Warden is not implemented.
  # Only reason to change this is for servers on which Mac login is not working and also which have Warden disabled.
  platform=Mac

  # Whether to treat server's MotD message as a server SYSTEM message.
  enable_server_motd=1

  version=2.4.3
  realmlist=logon.stormforge.gg
  realm=Public Test Realm - TBC
  account=discordbot
  password=XXXXXXXXXXX
  character=Discordbot

}

# guild notifications
guild {
  online {
    enabled=1
    format="`[%user] has come online.`"
  }
  offline {
    enabled=1
    format="`[%user] has gone offline.`"
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
  }
  demoted {
    enabled=1
    format="`[%user] has demoted [%target] to [%rank].`"
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
  }
  removed {
    enabled=1
    format="`[%target] has been kicked out of the guild by [%user].`"
  }
  motd {
    enabled=1
    format="`Guild Message of the Day: %message`"
  }
  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"
  }
}

# chat to redirect
chat {
  channels=[
    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=1067406797025050644
        format="[%user]: %message"
      }
    }
    {
      direction=discord_to_wow
      discord {
        channel=1067406797025050644
        format="[%user]: %message"
      }
      wow {
        type=Guild
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=System
      }
      discord {
        channel=1067406797025050644
        format="[SYSTEM]: %message"
      }
    } 
  ]
}

filters {
  enabled=0
  # patterns are Java Regexes. Google has the answers you seek.
  patterns=[
    ".*(?i)(?=.*g.?ld)(?=.*level)(?=.*item).*$" # case insensitive filter for messages containing all 3 words g?ld, level, and item in any order
    ".*(?=.*>>)(?=.*<<).*$" # filter for messages containg >> and << in any order (both must be in the message)
  ]
}

**Comment by fjaros** [comment]
Once again, Discord has added an extra hoop you have to jump through. You need to enable MESSAGE CONTENT INTENT in the developer portal under Bot:
![image](https://user-images.githubusercontent.com/541364/220727072-9ab2a094-d828-45e5-b94f-506d2b25d7c1.png)
