### ISSUE TITLE
One-way Connection only , Game->Discord

### ISSUE THREAD

**Issue by ghostown-servers** [fjaros/wowchat#88]
As in topic only one way seems to work , I cant reply or use any Bot "?" commands also "." commands from Discord side seems to do nothing.
Everything seems to look fine when message from Game is transmitted to  Discord, Here's my configuration of the channels :

# guild notifications
guild {
  online {
    enabled=1
    format="`[%user] has come online.`"
  }
  offline {
    enabled=1
    format="`[%user] has gone offline.`"
  }
  promoted {
    enabled=1
    format="`[%user] has promoted [%target] to [%rank].`"
  }
  joined {
    enabled=1
    format="`[%user] has joined the guild.`"
  }
  left {
    enabled=1
    format="`[%user] has left the guild.`"
  }
  motd {
    enabled=1
    format="`Guild Message of the Day: %message`"
  }
  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"
  }
}

# chat to redirect
chat {
  channels=[
    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[%user]: %message"
      }
    }
    {
      direction=wow_to_discord
      wow {
        type=System
      }
      discord {
        channel=world-chat
        format="[SYSTEM]: %message"
      }
    }
    {
      direction=both
      wow {
        type=Channel
        channel=commands
        format="[%user]: %message"
      }
      discord {
        channel=wotlk-chat
        format="[%target] [%user]: %message"
      }
    }
  ]
}

filters {
  enabled=0

**Comment by fjaros** [comment]
You have to enable Message Content Intent in Discord developer portal.
![image](https://user-images.githubusercontent.com/541364/222988481-e09901d9-b571-44b8-8248-99cb66503af3.png)
