### ISSUE TITLE
Parse Trade chat links and replace with db link

### ISSUE THREAD

**Issue by ForesterDev** [fjaros/wowchat#9]
Professions links create some trash in chat

![23213131](https://user-images.githubusercontent.com/11771800/49737624-c2563380-fca6-11e8-8d0e-509cd0838fa2.png)

I think, we need to parse them and replace with link to the DB with skill.

F.e. http://db.logon3.com/?skill=171 for alchemy

**Comment by fjaros** [comment]
Fixed in v1.2.6
