### ISSUE TITLE
Filters function not working

### ISSUE THREAD

**Issue by Brain-Hurts** [fjaros/wowchat#95]
Cannot get the filters function to filter anything out, including the java regexes already in the conf. 

Messages with >> and << don't get filtered.

Filters enabled is set to =1

Not getting any error to report

**Comment by fjaros** [comment]
Well just to make sure, can you paste the filter section of your config?
Do you see any logs with the word "FILTERED" showing up in the console window?

The filtering happens [here](https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/discord/Discord.scala#L73)
The shouldFilter function is [here](https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/discord/Discord.scala#L292) 

If you are sure your setup is correct, maybe you can add a log for what actually gets passed into shouldFilter and then we can debug why it is not being matched by any regex.

**Comment by Brain-Hurts** [comment]
I was tired last night and got it figured out today. Was just me being stupid with regex. Sorry for wasting your time.
