### ISSUE TITLE
%user issue

### ISSUE THREAD

**Issue by Annyelicious** [fjaros/wowchat#98]
Hi, I recently downloaded the lastest version of the bot with last changes to upgrade it, but now the names are bugged or something

![image](https://user-images.githubusercontent.com/53169828/235347432-0229bdaa-1098-4b9e-9d47-65e8519487fd.png)

<img width="818" alt="Screen Shot 2023-04-30 at 04 32 18" src="https://user-images.githubusercontent.com/53169828/235347435-0841b3fb-6fd7-4dfa-a63b-5738c000024d.png">

I saw another post with the same issue on another server, hope will be easy to solve

**Comment by fjaros** [comment]
Thanks for the report! I have fixed this for MoP and also added a fix to correctly invalidate player usernames in https://github.com/fjaros/wowchat/commit/fd310887737d1c358586b27adb1285a58a612f40 . Download the latest zip from Releases.
As MoP servers get more popular and the bot gets more traction on them, more bugs are found 😅
