### ISSUE TITLE
Sending Message from Ingame guild chat to discord

### ISSUE THREAD

**Issue by MrTide** [fjaros/wowchat#99]
Hello
After installing and going through the lovely wowchat <3 i figured out i have an issue so i was wondering if this is something that can be changed without compiling wowchat again (which is beyond my ability without step by step guide)
the server i am on got a different packet than what it is in the wowchat (6434)
![image](https://user-images.githubusercontent.com/36106057/235381617-ce9d0e44-34e3-4920-943c-6b6e70ab986f.png)

i am not really good at this but with help of a very dear friend we figured out this is why its not showing the messages in my discord, its reading it but not sending it
I was wondering if there is a easier way around this and i am using cataclysm 4.3.4.
maybe some config that we can change it or implemented when you felt like it.
Thank you in advance.

**Comment by fjaros** [comment]
Thanks for the report! Yeah 5 years ago a lot of the packets weren't really released in the open source world for cata so some of them are wrong. Fixed in https://github.com/fjaros/wowchat/commit/b55fdb1b11cb380a72bca3d9aff44d7b215e5a7d . Wouldn't mind the opcode for 5.4.8 too if you have it :)
